# Generated by Django 4.1.3 on 2023-01-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anab_app', '0004_actu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renouvellement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=250)),
                ('Prenom', models.CharField(max_length=250)),
                ('Carte_etudiant', models.FileField(upload_to='documents/')),
                ('Recu', models.FileField(upload_to='documents/')),
                ('Releve_Notes', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
