# Generated by Django 4.1.3 on 2023-01-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anab_app', '0005_renouvellement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renouvellement',
            name='Carte_etudiant',
        ),
        migrations.RemoveField(
            model_name='renouvellement',
            name='Recu',
        ),
        migrations.RemoveField(
            model_name='renouvellement',
            name='Releve_Notes',
        ),
    ]
