# Generated by Django 4.1.3 on 2023-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anab_app', '0006_remove_renouvellement_carte_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renouvellement',
            name='Carte_etudiant',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='renouvellement',
            name='Recu',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='renouvellement',
            name='Releve_Notes',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
