# Generated by Django 4.1.3 on 2023-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anab_app', '0008_alter_renouvellement_carte_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='renouvellement',
            name='Carte_etudiant',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='renouvellement',
            name='Recu',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='renouvellement',
            name='Releve_Notes',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
