# Generated by Django 4.1.3 on 2023-01-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anab_app', '0009_service_slug_alter_renouvellement_carte_etudiant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Renouvellement',
            new_name='DeamamdeSimple',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
