# Generated by Django 4.1.3 on 2023-01-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anab_app', '0010_rename_renouvellement_deamamdesimple_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeamamdeSimple',
            new_name='DemandeSimple',
        ),
    ]
