# Generated by Django 4.1.3 on 2023-01-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anab_app', '0012_rename_carte_etudiant_demandesimple_carte_d_etudiant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandesimple',
            name='Type_De_Demande',
        ),
    ]
