# Generated by Django 4.1.3 on 2023-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anab_app', '0013_remove_demandesimple_type_de_demande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandesimple',
            old_name='Releve_De_Notes',
            new_name='Releve_Notes',
        ),
        migrations.AddField(
            model_name='demandesimple',
            name='Type_De_Demande',
            field=models.CharField(choices=[('option1', 'Demande de Renouvellement de la bourse'), ('option2', 'Demande de Remboursement des frais de scolarites')], default='Demande de Renouvellement de la bourse', max_length=100),
        ),
    ]
